### ISSUE TITLE
[Bug] Adjust some words that are missing image.

### ISSUE THREAD

**Issue by epaiva** [mathiasfc/learning-english#1]
**Describe the bug**

Some words that are missing image.

- throughout
- necessary
- poor
- television
- charge

**To Reproduce**

Go to word URL, eg: [https://learning-english.vercel.app/words/charge/](https://learning-english.vercel.app/words/charge/)

**Screenshots**

![image](https://user-images.githubusercontent.com/43867513/197872345-6f402939-2f36-4630-bec7-23d210924012.png)

**Comment by mathiasfc** [comment]
Hey, thanks for raising these issues, I look forward to your PR!

**Comment by S-YUVARAJ** [comment]
can you assign this to me

**Comment by S-YUVARAJ** [comment]
@mathiasfc 
It would be a good exposure for me and i would be very grateful to you, as i am a beginner in open source contributions
Thanking You in advance

Regards
S Yuvaraj

**Comment by mathiasfc** [comment]
if @epaiva doesn't mind, sure, no problem... And I know the application got more image issues, so you can find and fix that, It will be a pleasure to have your contribution.

**Comment by S-YUVARAJ** [comment]
Thanks a lot, i will try to complete it as soon as possible

**Comment by epaiva** [comment]
@mathiasfc No problem :) 

If I find other words with errors, I open another issue.

**Comment by pulkithanda** [comment]
@mathiasfc Can I also work on this issue? You can label mine as hacktoberfest accepted?

**Comment by mathiasfc** [comment]
@pulkithanda this issue already been fixed, but you can find another broken images and fix it, just open another issue with listing the words that have image or text problem
