### ISSUE TITLE
[Bug] Words missing image

### ISSUE THREAD

**Issue by epaiva** [mathiasfc/learning-english#2]
**Describe the bug**

I find more words that are missing image.

- debate
- gas
- receive
- responsibility
- recognize
- scene
- rule
- population

**To Reproduce**

Go to word URL, eg: [https://learning-english.vercel.app/words/debate/
](https://learning-english.vercel.app/words/debate/
)
**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/43867513/197880106-a00e12d7-b0ad-4380-b4ef-f21ecf06b178.png)

**Comment by mathiasfc** [comment]
Thanks again! Go for it.
