### ISSUE TITLE
[Feature Request] Dynamic interval for auto advance mode

### ISSUE THREAD

**Issue by mathiasfc** [mathiasfc/learning-english#3]
**Is your feature request related to a problem? Please describe.**

Possibility to set a time interval for "auto advance" mode.

It would be interesting that the user can only change the slider if the auto-advance mode is enabled

**Describe the solution you'd like**

For example, create an slider below the auto advance toggle, to select the time between each word.

![image](https://user-images.githubusercontent.com/11564356/197881293-980e3173-77f3-4c5a-bc13-890544c44101.png)

E.g: [Material UI Slider](https://mui.com/material-ui/react-slider/)

![image](https://user-images.githubusercontent.com/11564356/197881217-734cbfd1-8f4a-494f-b892-978c8365a354.png)

**Comment by ewatch** [comment]
I already created a drafted PR. I am still working at it and I think I will finish it tomorrow.
