### ISSUE TITLE
[Bug] Auto advance mode not working as expected

### ISSUE THREAD

**Issue by mathiasfc** [mathiasfc/learning-english#4]
**Describe the bug**

When auto advance mode is enabled, the app advance correctly, but if the user clicks on "Next Word Button" at the bottom center, 

![image](https://user-images.githubusercontent.com/11564356/197882624-80108295-9627-461d-adf2-0745ad515b87.png)

The auto-advances mode bugs completely, starts passing words wuickly :bug:

I think this is related to the auto advances timer, we need to reset timer on every manually advance.

**To Reproduce**
1. Go to any word URL, e.g: [https://learning-english.vercel.app/words/animal/](https://learning-english.vercel.app/words/animal/)
2. Click on Settings icon at the top right corner.
3. Enable "Auto advances" mode.
4. Click multiples time on "Next Word"
5. See error

**Expected behavior**

Go forward without stopping, staying the same time at each word.

**Comment by P-DR0ZD** [comment]
could I look at this

**Comment by maemreyo** [comment]
I can fix this issue, please assign it to me. Thanks!

**Comment by maemreyo** [comment]
I already created a PR #13 , please review it
And don't forget to assign this issue to me
Thanks!
