### ISSUE TITLE
[Feature Request] API Integration to display meaning of word

### ISSUE THREAD

**Issue by anu-phoenix** [mathiasfc/learning-english#7]
**Is your feature request related to a problem? Please describe.**
Currently it shows the example. We can use public API integration to display meaning of word.

**Describe the solution you'd like**
Meaning is better to understand the word

**Describe alternatives you've considered**
Another alternative is to update a file containing the details of words.

**Additional context**
NA

**Comment by anu-phoenix** [comment]
Please assign me this, if you consider to do so.

**Comment by mathiasfc** [comment]
wow, @anu-phoenix it will be really nice to have the meaning of the word! Excited to see your PR 😊
