### ISSUE TITLE
Add a Female voice toggle for hearing the sentences

### ISSUE THREAD

**Issue by malay5** [mathiasfc/learning-english#8]
**Is your feature request related to a problem? Please describe.**
It is very often that females find it difficult to hear, what male pronuciation is, due to the deep male voice. 

**Describe the solution you'd like**
I would like to add a female voice toggle, so that the learners can toggle between female and male voices

**Additional context**
Please assign this issue to me, under hacktoberfest 2022

**Comment by malay5** [comment]
Please assign this issue to me under hacktoberfest22

**Comment by mathiasfc** [comment]
@malay5 Hey! Great points, increase accessibility, go for it :)
